import { createId, isCuid } from '@paralleldrive/cuid2'

/** All app entity ids are CUIDs (generated by `public.cuid()` in Postgres). Use this for client-side ids (e.g. file names). */
export const newId = createId
export const isEntityId = isCuid
